# Generated by Django 5.0.3 on 2025-07-24 07:29

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_contactmessage'),
    ]

    operations = [
        migrations.RenameField(
            model_name='testimonial',
            old_name='quote',
            new_name='content',
        ),
        migrations.RemoveField(
            model_name='testimonial',
            name='is_published',
        ),
        migrations.RemoveField(
            model_name='testimonial',
            name='position',
        ),
        migrations.AddField(
            model_name='contactmessage',
            name='phone',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='testimonial',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
